name: Release Userscript

on:
  push:
    tags:
      - 'v*.*.*'  # Only trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ steps.get_version.outputs.VERSION }}"
          body: |
            ## MiniBlox Wallpaper Update v${{ steps.get_version.outputs.VERSION }}
            
            ### Installation
            Click the asset below to install/update the userscript.
            
            ### Changes
            See commit history for detailed changes.
          files: miniblox.user.js
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
